stages:
  data_preprocessing:
    cmd: python scripts/preprocess_data.py
    deps:
    - data/raw/emails.csv
    - scripts/preprocess_data.py
    outs:
    - data/processed/clean_emails.csv
    metrics:
    - data/processed/data_quality_report.json

  train_intent_classifier:
    cmd: python scripts/train_models.py --model intent_classifier
    deps:
    - data/processed/clean_emails.csv
    - scripts/train_models.py
    outs:
    - models/intent_classifier/
    metrics:
    - models/intent_classifier/metrics.json
    plots:
    - models/intent_classifier/confusion_matrix.json

  train_reply_generator:
    cmd: python scripts/train_models.py --model reply_generator
    deps:
    - data/processed/clean_emails.csv
    - scripts/train_models.py
    outs:
    - models/reply_generator/
    metrics:
    - models/reply_generator/metrics.json
    plots:
    - models/reply_generator/performance_plot.json

  evaluate_models:
    cmd: python scripts/evaluate_models.py
    deps:
    - models/intent_classifier/
    - models/reply_generator/
    - data/processed/clean_emails.csv
    - scripts/evaluate_models.py
    outs:
    - data/processed/evaluation_output.csv
    metrics:
    - models/evaluation_metrics.json

  validate_models:
    cmd: python scripts/validate_models.py
    deps:
    - models/intent_classifier/
    - models/reply_generator/
    - scripts/validate_models.py
    metrics:
    - models/validation_report.json