# MLOps Configuration
mlops:
  # MLflow Configuration
  mlflow:
    tracking_uri: "sqlite:///mlops/mlruns.db"
    experiment_name: "email_assistant"
    artifact_location: "./mlops/artifacts"
    
  # Model Registry Settings
  model_registry:
    auto_promotion: true
    performance_thresholds:
      intent_classifier:
        accuracy: 0.85
        f1_score: 0.80
        precision: 0.80
        recall: 0.80
      reply_generator:
        bleu_score: 0.30
        rouge_score: 0.25
        
  # Drift Detection Settings
  drift_detection:
    enabled: true
    data_drift_threshold: 0.05  # p-value for statistical tests
    model_drift_threshold: 0.1  # performance degradation threshold
    monitoring_window_days: 7
    features_to_monitor:
      - email_length
      - word_count
      - sentiment_score
      - domain_type
      
  # Data Quality Settings
  data_quality:
    validation_rules:
      - column: "email_text"
        type: "not_null"
      - column: "email_text"
        type: "min_length"
        value: 10
      - column: "intent"
        type: "categorical"
        allowed_values: ["inquiry", "complaint", "request", "feedback"]
        
  # Model Validation Settings
  model_validation:
    test_size: 0.2
    cross_validation_folds: 5
    minimum_accuracy: 0.75
    
  # Monitoring Settings
  monitoring:
    enabled: true
    check_interval_hours: 6
    alert_thresholds:
      accuracy_drop: 0.1
      latency_increase: 2.0  # seconds
      error_rate: 0.05
      
  # Retraining Settings
  retraining:
    auto_retrain: true
    trigger_conditions:
      - drift_detected: true
      - performance_drop: 0.1
      - data_volume_increase: 1000  # new samples
    schedule: "0 2 * * 0"  # Weekly on Sunday at 2 AM
    
  # Deployment Settings
  deployment:
    staging_environment: "staging"
    production_environment: "production"
    health_check_endpoint: "/health"
    rollback_enabled: true
    
  # Logging and Alerting
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
  alerting:
    enabled: true
    channels:
      - type: "email"
        recipients: ["ml-team@company.com"]
      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
